---
# tasks file for nfs_client
- name: Install nfs-common
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: yes
  become: true

- name: Create a directory /opt/nfs/file
  ansible.builtin.file:
    path: /opt/nfs/file
    state: directory
    mode: '0777'
  become: true

#- name: Mount an NFS volume local tests
#  ansible.posix.mount:
#    src: 192.168.172.145:/opt/files
#    path: /opt/nfs/file/
#    opts: rw,sync,hard
#    state: mounted
#    fstype: nfs
#  become: true

- name: Mount an NFS volume
  ansible.posix.mount:
    src: www.file01.shabalin.site:/opt/files
    path: /opt/nfs/file/
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
  become: true
